# Generated by Django 3.2.5 on 2021-10-16 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_chat_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedata',
            name='image',
        ),
        migrations.AddField(
            model_name='messagedata',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('video', 'video'), ('file', 'file')], max_length=10),
        ),
    ]
